blank_issues_enabled: false
contact_links:
  - name: Security advisories
    url: https://github.com/SharifdotG/REPO/security/advisories/new
    about: Please use the private advisory workflow for security vulnerabilities.
